# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AppServiceBG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://appservicecr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_95b16af5d32640238498a8e110540569 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_716d2b4be9ca45cb8740385ebe9d0026 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: appservicecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_95b16af5d32640238498a8e110540569 }}/appservicebg:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AppServiceBG'
        slot-name: 'green'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_82a820f1731341579b32f99b8d33bf9f }}
        images: 'appservicecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_95b16af5d32640238498a8e110540569 }}/appservicebg:${{ github.sha }}'
