# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appservicebg(green)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://appservicecr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d3dbc2811c54499d9a7ff61b42b5bbc6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b6730dd89c614d19929fbd72c5388454 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: appservicecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3dbc2811c54499d9a7ff61b42b5bbc6 }}/appservicecr/appservicebg:${{ github.sha }}
        file: ./Dockerfile
        
  approve:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Approval
        uses: paul-newman/request-approval-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 'henriqcabral, rocko83'
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'green'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appservicebg'
        slot-name: 'green'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_11de10ab753d4f5c92a7b33e0751ad48 }}
        images: 'appservicecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d3dbc2811c54499d9a7ff61b42b5bbc6 }}/appservicecr/appservicebg:${{ github.sha }}'